# Copyright 2022 OpenHW Group
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
# Run all lint checks
name: lint
on: [push, pull_request]
jobs:
  #####################
  # Vendor Up-to-Date #
  #####################
  # Check that all vendored sources are up-to-date.
  check-vendor:
    name: Vendor Up-to-Date
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vlsi-lab/x-heep-toolchain:experimental
    steps:
    - name: Checkout the pushed code. 
      uses: actions/checkout@v3
    - name: Re-vendor and diff
      run: |
        conda init bash
        source /root/.bashrc
        conda activate core-v-mini-mcu
        make clean-all
        find . \
        -name '*.vendor.hjson' \
        | xargs -n1 util/vendor.py --verbose \
        && util/git-diff.py --error-msg "::error ::Found differences, please re-vendor."
  ##################
  # MCU Generator  #
  ##################
  mcu_generator:
    name: Generates sv files
    # This job runs on Linux (fixed ubuntu version)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vlsi-lab/x-heep-toolchain:experimental
    name: Simulate all apps. All must pass.
    steps:
      - name: Checkout the pushed code. 
        uses: actions/checkout@v3
    - name: Run Gen
      run: |
        conda init bash
        source /root/.bashrc
        conda activate core-v-mini-mcu
        make clean-all
        make mcu-gen
        util/git-diff.py --error-msg "::error ::Found differences in SystemVerilog files generated with default configuration."
